services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      MONGODB_URI: mongodb://mongo:27017/spotify-fm
    depends_on:
      - redis
      - mongo 

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    # Downgraded from MongoDB 8.x as it doesn't start on Linux kernels 6.19 - 7.0.13
    # 7.0 works on all kernels: https://jira.mongodb.org/browse/SERVER-125742
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data:
