/* This file has been mostly generated by AI */

import { Schema, model, models, type Model } from 'mongoose';
import type { SpotifyFavorite } from '../types/schemas';

const favoriteDbSchema = new Schema<SpotifyFavorite>(
  {
    userId: { type: String, required: true },
    trackId: { type: String, required: true },
    track: { type: Schema.Types.Mixed, required: true },
  },
  { versionKey: false, timestamps: { createdAt: true, updatedAt: false } }
);

favoriteDbSchema.index({ userId: 1, trackId: 1 }, { unique: true });
favoriteDbSchema.index({ userId: 1, createdAt: -1 });

export const FavoriteModel =
  (models.Favorite as Model<SpotifyFavorite> | undefined) ??
  model<SpotifyFavorite>('Favorite', favoriteDbSchema);
