/* This file has been mostly generated by AI */

import { Schema, model, models } from 'mongoose';

const favoriteDbSchema = new Schema(
  {
    userId: { type: String, required: true },
    trackId: { type: String, required: true },
    track: { type: Schema.Types.Mixed, required: true },
  },
  { timestamps: { createdAt: true, updatedAt: false } }
);

favoriteDbSchema.index({ userId: 1, trackId: 1 }, { unique: true });
favoriteDbSchema.index({ userId: 1, createdAt: -1 });

export const FavoriteModel = models.Favorite ?? model('Favorite', favoriteDbSchema, 'favorites');
