/* This file has been mostly generated by AI */

import { Schema, model, models, type Model } from 'mongoose';
import type { Snapshot } from '../types/schemas';

const snapshotDbSchema = new Schema<Snapshot>(
  {
    date: { type: String, required: true, unique: true },
    tracks: { type: Schema.Types.Mixed, required: true },
  },
  { versionKey: false, timestamps: { createdAt: true, updatedAt: false } }
);

snapshotDbSchema.index({ createdAt: 1 }, { expireAfterSeconds: 60 * 60 * 24 * 365 });

export const SnapshotModel =
  (models.Snapshot as Model<Snapshot> | undefined) ?? model<Snapshot>('Snapshot', snapshotDbSchema);
